### ISSUE TITLE
Issue: adding ad about this project

### ISSUE THREAD

**Issue by lzkelley** [linouk23/NBA-Player-Movements#2]

**Comment by christopherjenness** [comment]
I agree.  However, I appreciated seeing this specific project.

**Comment by linouk23** [comment]
I'm sorry you got it this way; some users were really happy to find out about this project though.
- ![1](https://s10.postimg.org/m5r1avq49/image.png)
- ![2](https://s9.postimg.org/f51w5fn27/image.png)

@lzkelley thanks anyway though, stop doing it from this moment.
